### ISSUE TITLE
Compilation issue: Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by daljeet16** [ricwein/CircleProgressView#1]
We are using UICircleProgressView 0.6.1, and updated Xcode to version 15. After update we are getting compilation error below:
`Stored properties cannot be marked unavailable with '@available'`
in class `UICircleProgressButton` and `UICircleProgressView`
Please update!

**Comment by ricwein** [comment]
Thanks for your feedback. Should be fixed with v0.6.2.

**Comment by EInfochips-Priyank** [comment]
Hey @ricwein , could you please update the version from 0.6.1 to 0.6.2 in UICircleProgressView.podspec? I'm eager to grab the latest version from your repository. Thanks!"

**Comment by ricwein** [comment]
Hey. Sorry for the late response. I've updated the podspec and release the matching new version 0.6.3. Hopfully this works for you ;)
